// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0MwXDYVvS3c-kYh4H4sfrszHGvEnEYTY',
    appId: '1:445585846691:web:4b0eacc581814c7278aa16',
    messagingSenderId: '445585846691',
    projectId: 'ssu-prime',
    authDomain: 'ssu-prime.firebaseapp.com',
    storageBucket: 'ssu-prime.firebasestorage.app',
    measurementId: 'G-X0MR85YJZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSgNQrLJNNNBDAtnCcgG8jR2CrDMMs--8',
    appId: '1:445585846691:android:3ba2f48bf527ddef78aa16',
    messagingSenderId: '445585846691',
    projectId: 'ssu-prime',
    storageBucket: 'ssu-prime.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcxQMmGlL5e_kp59VpAdbsQr9hEEgFa8g',
    appId: '1:445585846691:ios:0af4aa2169a99a7078aa16',
    messagingSenderId: '445585846691',
    projectId: 'ssu-prime',
    storageBucket: 'ssu-prime.firebasestorage.app',
    iosBundleId: 'com.example.ssuPrime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcxQMmGlL5e_kp59VpAdbsQr9hEEgFa8g',
    appId: '1:445585846691:ios:0af4aa2169a99a7078aa16',
    messagingSenderId: '445585846691',
    projectId: 'ssu-prime',
    storageBucket: 'ssu-prime.firebasestorage.app',
    iosBundleId: 'com.example.ssuPrime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0MwXDYVvS3c-kYh4H4sfrszHGvEnEYTY',
    appId: '1:445585846691:web:2b04f4ed68c05b5478aa16',
    messagingSenderId: '445585846691',
    projectId: 'ssu-prime',
    authDomain: 'ssu-prime.firebaseapp.com',
    storageBucket: 'ssu-prime.firebasestorage.app',
    measurementId: 'G-KHNTZGB9WL',
  );
}
